on: [pull_request]

env:
  TEST_TAG: invoice-utils:test
  WORKSPACE: /opt/invoice-utils
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: Continuous Integration
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Tests
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.TEST_TAG }}
          options: --rm -v ${{ github.workspace }}/dist:${{env.WORKSPACE}}/dist
          run: poetry run pytest --junit-xml ./dist/test-results.xml tests/
      - name: Record Test Results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: ./dist/test-results.xml
          summary: true
          fail-on-empty: true
          title: Automated Tests
