name: invoice-utils 

on: push

permissions:
  contents: read


jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      image: docker:20.10.11
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t invoice-utils -f Dockerfile .

      - name: Run tests
        run: docker run --rm invoice-utils test
