name: invoice-utils 

on: push

permissions:
  contents: read


jobs:
  run-tests:
    runs-on: ubuntu-latest
      container: 
        image: 'Dockerfile'
      steps:
        - name: Run tests
          run: docker build --target test -t test .
